export const QUESTIONS = [
  {
    id: "q1",
    section: "Osnovni podaci",
    label: "Discord ime i ID",
    type: "short",
    required: true,
    placeholder: "npr. korisnik#1234 ili korisnik (123456789012345678)",
  },
  {
    id: "q2",
    section: "Osnovni podaci",
    label: "IC ime i prezime",
    type: "short",
    required: true,
    placeholder: "Ime Prezime lika na serveru",
  },
  {
    id: "q3",
    section: "Iskustvo i aktivnost",
    label: "Koliko dugo igrate na ONIX Roleplay?",
    type: "short",
    required: true,
    placeholder: "npr. 3 mjeseca, 1 godina",
  },
  {
    id: "q4",
    section: "Iskustvo i aktivnost",
    label: "Koliko ste dnevno aktivni na serveru i u kojim terminima ste najčešće dostupni?",
    type: "long",
    required: true,
    placeholder: "Navedi sate dnevno i termine (npr. 18:00–02:00).",
  },
  {
    id: "q5",
    section: "Iskustvo i aktivnost",
    label: "Koliko ukupno iskustva imate u PD-u i na rukovodećim pozicijama?",
    type: "long",
    required: true,
    placeholder: "Serveri, organizacije, pozicije, period.",
  },
  {
    id: "q6",
    section: "Motivacija",
    label: "Zašto smatrate da ste upravo vi osoba za Chief poziciju?",
    type: "long",
    required: true,
    placeholder: "Konkretno objasni zašto si pravi izbor.",
  },
  {
    id: "q7",
    section: "Plan rada",
    label: "Koji su vaši prvi ciljevi u prvih 7 dana nakon preuzimanja PD-a?",
    type: "long",
    required: true,
    placeholder: "Prioriteti, struktura, aktivnost, obuke.",
  },
  {
    id: "q8",
    section: "Plan rada",
    label: "Kako biste povećali aktivnost članova PD-a i spriječili neaktivnost?",
    type: "long",
    required: true,
    placeholder: "Konkretne mjere, ne opšte rečenice.",
  },
  {
    id: "q9",
    section: "Plan rada",
    label: "Koliko vremena ste spremni konkretno posvetiti vođenju PD-a svakog dana?",
    type: "short",
    required: true,
    placeholder: "npr. 4–6 sati dnevno",
  },
  {
    id: "q10",
    section: "Organizacija PD-a",
    label: "Kako biste organizovali činove, smjene, obuke i napredovanja?",
    type: "long",
    required: true,
    placeholder: "Hijerarhija, smjene, akademija, kriteriji napredovanja.",
  },
  {
    id: "q11",
    section: "Organizacija PD-a",
    label: "Šta biste uradili sa članom koji ima visok čin, ali je neaktivan i ne izvršava svoje obaveze?",
    type: "long",
    required: true,
    placeholder: "Postupak, rokovi, posljedice.",
  },
  {
    id: "q12",
    section: "Situaciona pitanja",
    label: "Kako biste postupili kada policajac kojeg dobro poznajete napravi ozbiljan prekršaj?",
    type: "long",
    required: true,
    placeholder: "Odgovori kao Chief, ne kao igrač.",
  },
  {
    id: "q13",
    section: "Situaciona pitanja",
    label: "Kako biste riješili sukob između dva visoko rangirana člana PD-a?",
    type: "long",
    required: true,
    placeholder: "Koraci, disciplina, odluka.",
  },
  {
    id: "q14",
    section: "Situaciona pitanja",
    label: "Šta biste uradili ako većina članova PD-a nije zadovoljna vašim načinom vođenja?",
    type: "long",
    required: true,
    placeholder: "Komunikacija, promjene, odgovornost.",
  },
  {
    id: "q15",
    section: "Situaciona pitanja",
    label: "Kako biste osigurali da PD bude aktivan i kada nema većeg broja igrača na serveru?",
    type: "long",
    required: true,
    placeholder: "Aktivnosti, patrola, obuke, dogovori.",
  },
  {
    id: "q16",
    section: "Situaciona pitanja",
    label: "Kako biste održavali balans između ozbiljnog RP-a i zabave za članove PD-a?",
    type: "long",
    required: true,
    placeholder: "Standard, disciplina, atmosfera.",
  },
  {
    id: "q17",
    section: "Plan rada",
    label: "Koje biste konkretne promjene uveli u trenutni sistem PD-a?",
    type: "long",
    required: true,
    placeholder: "Pravila, rankovi, procesi, aktivnosti.",
  },
  {
    id: "q18",
    section: "Organizacija PD-a",
    label: "Kako biste spriječili nepotizam i davanje činova prijateljima?",
    type: "long",
    required: true,
    placeholder: "Sistem promocija, transparentnost, kazne.",
  },
  {
    id: "q19",
    section: "Situaciona pitanja",
    label: "Kako biste reagovali ako član PD-a odbije naređenje višeg čina bez opravdanog razloga?",
    type: "long",
    required: true,
    placeholder: "Disciplinski postupak.",
  },
  {
    id: "q20",
    section: "Situaciona pitanja",
    label: "Kako biste postupili ako drugi Chief/Head Staff ospori vašu odluku?",
    type: "long",
    required: true,
    placeholder: "Komunikacija, argumenti, poštovanje hijerarhije.",
  },
  {
    id: "q21",
    section: "RP standard",
    label: "Šta za vas znači kvalitetan Police RP na Medium RP serveru?",
    type: "long",
    required: true,
    placeholder: "Definicija kvaliteta, primjeri, očekivanja.",
  },
  {
    id: "q22",
    section: "Situaciona pitanja",
    label: "Navedite primjer ozbiljne situacije u kojoj biste morali donijeti nepopularnu odluku kao Chief. Kako biste je riješili?",
    type: "long",
    required: true,
    placeholder: "Konkretan scenarij i postupak.",
  },
  {
    id: "q23",
    section: "RP standard",
    label: "Koliko ste spremni prihvatiti kritiku i odgovornost za greške svog PD-a?",
    type: "long",
    required: true,
    placeholder: "Iskren odgovor o odgovornosti.",
  },
  {
    id: "q24",
    section: "Motivacija",
    label: "Šta će ONIX dobiti vašim dolaskom na poziciju Chiefa?",
    type: "long",
    required: true,
    placeholder: "Aktivnost, kvalitet, struktura, ljudi.",
  },
  {
    id: "q25",
    section: "Plan rada",
    label: "Napišite detaljan plan rada za prvih 30 dana vođenja PD-a.",
    type: "long",
    required: true,
    placeholder: "Sedmice, ciljevi, mjerljivi rezultati.",
  },
  {
    id: "q26",
    section: "Iskustvo i aktivnost",
    label: "Obavezno navedite koliko možete biti aktivni sedmično i da li imate periode kada nećete biti dostupni.",
    type: "long",
    required: true,
    placeholder: "Sati sedmično + eventualni AFK periodi.",
  },
  {
    id: "q27",
    section: "Motivacija",
    label: "Zašto bismo izabrali vas, a ne nekog drugog kandidata?",
    type: "long",
    required: true,
    placeholder: "Finalni argument — šta te izdvaja.",
  },
];

export const STATUS_LABELS = {
  novo: "Novo",
  u_razmatranju: "U razmatranju",
  prihvacen: "Prihvaćen",
  odbijen: "Odbijen",
};

export const SECTIONS = [...new Set(QUESTIONS.map((q) => q.section))];
